# Generated by Django 4.2.30 on 2026-05-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True, unique=True)),
                ("solar_kw", models.FloatField(help_text="PV output (kW)")),
                ("load_kw", models.FloatField(help_text="Hotel demand (kW)")),
                (
                    "grid_price_eur_per_kwh",
                    models.FloatField(help_text="TOU grid price (€/kWh)"),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DispatchInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "battery_kw",
                    models.FloatField(
                        help_text="Battery power (kW); +charge/-discharge"
                    ),
                ),
                (
                    "soc_pct",
                    models.FloatField(
                        help_text="State of charge at end of interval (%)"
                    ),
                ),
                (
                    "grid_kw",
                    models.FloatField(
                        help_text="Net grid draw (kW); always >= 0 (no export)"
                    ),
                ),
                ("curtailed_kw", models.FloatField(help_text="Solar curtailed (kW)")),
                (
                    "cost_eur",
                    models.FloatField(help_text="Grid spend this interval (€)"),
                ),
                (
                    "counterfactual_cost_eur",
                    models.FloatField(
                        help_text="Grid spend without battery this interval (€)"
                    ),
                ),
                (
                    "interval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="dispatch.energyinterval",
                    ),
                ),
            ],
            options={
                "ordering": ["interval__timestamp"],
            },
        ),
    ]
